GIT-SYNC(1)
===========
:doctype: manpage


NAME
----
git-sync - Syncs local changes with the server.


SYNOPSIS
--------
'git-sync' ['OPTIONS']


DESCRIPTION
-----------
'git-sync(1)' fetches the latest repository from the server, rebases/merges
the current branch against the changes in the integration branch, then pushes
the result up to a branch on the server of the same name. (Unless told not to.)

If there is a problem, such as a merge conflict, this tries to
resolve it automatically. If it can not do so in an automated way,
if tells you the steps involved for doing so manually.


OPTIONS
-------

*-r, --rebase*::
    Rebase instead of merge against the integration branch (*default: true*)

*--merge*::
    Merge instead of rebase against the integration branch

*-f, --force*::
    Force the push; defaults to true if --rebase is used

*-l, --local*::
    Do not do a push; gets remote changes, but does not update the server

*--info*::
    Informational messages; show the major things this is doing (*default: true*)

*-q, --quiet*::
    Quiet messages; only show errors

*-v, --verbose*::
    Verbose messages; show lots of details on what this is doing

*--version*::
    Print version and exit

*-h, --help*::
    Show this message


CONFIGURATION
-------------

Options for 'git-sync(1)' are set using 'git-config(1)'.

*gitProcess.remoteName*::
    Allows you to explicitly set the remote server name to use. Defaults
    to the first server name reported by 'git-remote(1)'.

*gitProcess.defaultRebaseSync*::
    Should 'git-sync(1)' use *--rebase* by default instead of *--merge*? Defaults to *true*.


EXAMPLE
-------

Assuming that the current branch is called "interesting_changes" and the integration
branch on the server is "master", typing "git sync" will do roughly the following
for you:

  $ git fetch -p
  $ git rebase origin/interesting_changes
  $ git rebase origin/master
  $ git push origin interesting_changes:interesting_changes


SEE ALSO
--------

*git-process*(1), *git-to-master*(1), *git-new-fb*(1), *git-pull-request*(1), *git-process-lib*(3)


BUGS
----
Known bug list: <https://github.com/jdigger/git-process/issues?state=open>


AUTHOR
------
git-sync has been written primarily by Jim Moore.


RESOURCES
---------
Main web site: <https://github.com/jdigger/git-process>
