= GIT-PROCESS(1) =
:doctype: manpage


== NAME ==
git-process - A suite of tools to make it easy to use an easy and robust git process.


== DESCRIPTION ==
'git-process(1)' consists of a small suite of tools that make it easy to follow a simple, consistent process
that scales from simple one-person projects to very large (dozens of developers) collaboration. It does this
by taking advantage of "classic" methodologies like "Git Flow" and GitHub pull requests to have "just enough"
process. See <<WE00,*WORKFLOW EXAMPLES*>> to see this in practice.


== COMMON OPTIONS ==

*--info*::
    Informational messages; show the major things this is doing (*default: true*)

*-q, --quiet*::
    Quiet messages; only show errors

*-v, --verbose*::
    Verbose messages; show lots of details on what this is doing

*--version*::
    Print version and exit


== CONFIGURATION ==

*gitProcess.remoteName*::
    Allows you to explicitly set the remote server name to use. Defaults
    to the first server name reported by 'git-remote(1)'.

*gitProcess.integrationBranch*::
    Allows you to explicitly set the integration branch to use. Defaults
    to "master".

*gitProcess.defaultRebaseSync*::
    Should 'git-sync(1)' use *--rebase* by default instead of *--merge*? Defaults to *true*.

*gitProcess.github.authtoken*::
    Not meant to be set manually, this is the OAuth token used to communicate
    with the GitHub server. If it is not set, the user will be prompted for their credentials.

*github.user*::
    If OAuth needs to prompt for credentials, if this value is set then it is
    used as the username. Otherwise it is unused.


[[WE00]]
== WORKFLOW EXAMPLES ==

=== WORKING ALONE ON A LOCAL-ONLY PROJECT ===

Jim is working on "my_project" and needs to start work on a new feature.

  [a_branch]$ git new-fb save_the_planet
    Creating save_tp off of master
  [save_the_planet]$

He does lots of work. Checkin, checkin, checkin.

A sudden new brilliant idea happens.

  [save_the_planet]$ git new-fb shave_the_bunnies
    Creating shave_the_bunnies off of master
  [shave_the_bunnies]$

After creating a Sheering class and tests, he commits his changes.

  [shave_the_bunnies]$ git commit
  [shave_the_bunnies]$ git to-master
    Rebasing shave_the_bunnies against master
    Removing branch 'shave_the_bunnies'
  [_parking_]$

Time to get back to work on "save_the_planet".

  [_parking_]$ git checkout save_the_planet
  [save_the_planet]$ git sync
    Rebasing save_the_planet against master
  [save_the_planet]$

Do more work. Commit. Commit. Commit.

  [save_the_planet]$ git sync
    Rebasing save_the_planet against master
  [save_the_planet]$

Liking to have a clean history, he squashes and edits the commits to hide
the evidence of false starts and stupid ideas so that anyone who sees the
code in the future will think he was simply a genius.

  [save_the_planet]$ git rebase -i
    Rebasing save_the_planet against master
  [save_the_planet]$ git to-master
    Rebasing save_the_planet against master
    Removing branch 'save_the_planet'
  [_parking_]$

Time to release to a grateful world.


=== WORKING WITH A TEAM ===

John, Alice, Bill and Sally are working on "big_monies." Alice and John are pairing and
need to start work on a new feature.

  john-[a_branch]$ git new-fb steal_underpants
    Fetching the latest changes from the server
    Creating steal_underpants off of origin/master
  john-[steal_underpants]$

They do lots of work. Checkin, checkin, checkin. It has a lot of steps...

Meanwhile Bill has been working on his great idea:

  bill-[some_branch]$ git new-fb awesomo4000
    Fetching the latest changes from the server
    Creating awesomo4000 off of origin/master
  bill-[awesomo4000]$

He creates his "Laaaaame" class and checks it in, with a pull request asking Sally to do a code review.

  bill-[awesomo4000]$ git commit
  bill-[awesomo4000]$ git pull-req "A.W.E.S.O.M-0 4000 prototype" \
                      -d "@sally, can you make sure Butters won't recognize it?"
    Pushing to 'awesomo4000' on 'origin'.
    Creating a pull request asking for 'awesomo4000' to be merged into 'master' on big_monies.
    Created pull request at https://github.com/big_monies/pull/3454
  bill-[awesomo4000]$

Sally sees the email. After looking at it in the web interface, she wants to test it.

  sally-[other_branch]$ git pull-req 3454
    Getting #pr_number
    Fetching the latest changes from the server
      new branch: awesomo4000
    Setting upstream/tracking for branch 'awesomo4000' to 'origin/master'.
  sally-[awesomo4000]$ git sync
    Fetching the latest changes from the server
    Rebasing awesomo4000 against origin/master
    Pushing to 'awesomo4000' on 'origin'.
  sally-[awesomo4000]$

After verifying that the tests still work and "it's all good" she promotes the code to integration.

  sally-[awesomo4000]$ git to-master
    Fetching the latest changes from the server
    Rebasing awesomo4000 against origin/master
    Pushing to 'awesomo4000' on 'origin'.
    Removing branch remote 'awesomo4000'
    Removing branch local 'awesomo4000'
    Closing a pull request #3454 on origin.
  sally-[_parking_]$

Over lunch Alice gets a brainstorm ("a duck and rubber hose!") and rushes off to her computer:

  alice-[lens_cap]$ git sync steal_underpants
    Fetching the latest changes from the server
    Creating steal_underpants off of origin/steal_underpants
    Setting upstream/tracking for branch 'steal_underpants' to 'origin/master'.
  alice-[steal_underpants]$

She makes her changes, syncs back up with the server, and heads over to pair with John again.

  alice-[steal_underpants]$ git commit
  alice-[steal_underpants]$ git sync
    Fetching the latest changes from the server
    Rebasing steal_underpants against origin/master
    Pushing to 'steal_underpants' on 'origin'.
  alice-[steal_underpants]$

John, meanwhile, had made some changes of his own.

  john-[steal_underpants]$ git commit
  john-[steal_underpants]$ git sync
    Fetching the latest changes from the server
    Remote branch has changed
    Rebasing steal_underpants against origin/steal_underpants
    Rebasing steal_underpants against origin/master
    Pushing to 'steal_underpants' on 'origin'.
  john-[steal_underpants]$

At this point, his local branch has Alice's change as well as Bill and
Sally's A.W.E.S.O.M-O 4000 enhancements.

After confirming with Alice and Bill that everything looks good, he
pushes his changes up for integration.

  john-[steal_underpants]$ git to-master
    Fetching the latest changes from the server
    Rebasing steal_underpants against origin/master
    Pushing to 'steal_underpants' on 'origin'.
    Removing remote branch 'steal_underpants'
    Removing local branch 'steal_underpants'
  [_parking_]$

Profit!!


== CONTROL FILES ==

*gitprocess-sync-\***--**::
    To help make the process simpler and more reliable, 'git-sync(1)' will put a file in the "'.git'" directory
    that contains the SHA-1 of the last successful sync to the server. 'git-to-master(1)' will remove the file
    as part of its normal "housekeeping."


== SEE ALSO ==

*git-sync*(1), *git-to-master*(1), *git-new-fb*(1), *git-pull-req*(1)


== BUGS ==
Known bug list: <https://github.com/jdigger/git-process/issues?state=open>


== AUTHOR ==
git-process has been written primarily by Jim Moore.


== RESOURCES ==
Main web site: <https://github.com/jdigger/git-process>
